// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
    "demo1/internal/pkg/job"
)

// Injectors from wire.go:

func SuperFactory() *job.Factory {
    work := job.NewWorkFunc()
    worker := job.NewWorker(work)
    builder := job.NewBuilder(worker)
    factory := job.NewFactory(builder)
    return factory
}
