// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package di

import (
	"license_kratos/internal/dao"
	"license_kratos/internal/license"
	"license_kratos/internal/server/http"
	"license_kratos/internal/service"
)

// Injectors from wire.go:

func InitApp() (*App, func(), error) {
	daoDao, cleanup, err := dao.New()
	if err != nil {
		return nil, nil, err
	}
	licenseLicense, err := license.NewLicense()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	serviceService, cleanup2, err := service.New(daoDao, licenseLicense)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	engine, err := http.New(serviceService)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	app, cleanup3, err := NewApp(serviceService, engine)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	return app, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
